# .ps_project/config.yaml:

version: 1


project: "prekhqj6a"
experiment: "media-classifier" #[optional, default:<repo name>]
type: "single" #[single|multi-grpc|multi-mpi]
ports: "5000" #[optional, default:5000]

paths: #[optional]
  workdir: "/path/to/workdir"
  artifacts: "/path/to/artifacts"
model: #[optional, but required for model parsing and model deployments]
  type: "model-type" #[required for model, one of: Tensorflow|ONNX|Custom]
  path: "/path/to/model"

worker:
  container: "tensorflow/tensorflow:2.0.0b1-gpu-py3"
  command: "nvidia-smi"
  machine-type: "K80"
  count:

checks: #[optional]
  tensorflow:loss:
    target: 0.0..0.5
    aggregate: "mean"
  defaults: #[optional]
    precision: 3
